"""Add fee configuration and withdrawal fee columns

Revision ID: 0086f1f2e2d0
Revises: 6f5a7a83f66e
Create Date: 2026-08-19 19:48:30.059440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0086f1f2e2d0'
down_revision: Union[str, Sequence[str], None] = '6f5a7a83f66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_entry_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('winning_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('withdrawal_fee_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('withdrawals', sa.Column('fee_amount', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('withdrawals', sa.Column('net_amount', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'net_amount')
    op.drop_column('withdrawals', 'fee_amount')
    op.drop_table('fee_configurations')
    # ### end Alembic commands ###

