"""Add LudoMatchmakingQueue

Revision ID: 3a4b59aa8650
Revises: c7e85984cc75
Create Date: 2026-08-20 05:56:43.470113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4b59aa8650'
down_revision: Union[str, Sequence[str], None] = 'c7e85984cc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ludo_matchmaking_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SEARCHING', 'MATCHED', 'CANCELLED', name='queue_status_enum'), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['ludo_matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ludo_matchmaking_queue')
    # ### end Alembic commands ###

