"""add_referrals

Revision ID: 605ad3473791
Revises: 7e4f2a1b9c80
Create Date: 2026-08-24 05:11:38.748315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605ad3473791'
down_revision: Union[str, Sequence[str], None] = '7e4f2a1b9c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reward_amount', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'QUALIFIED', 'REWARD_PAID', name='referral_status'), nullable=False),
    sa.Column('reward_amount', sa.BigInteger(), nullable=False),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reward_transaction_id'], ['wallet_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id', name='uq_referral_referred_user')
    )
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.drop_constraint(op.f('rummy_tables_join_code_key'), 'rummy_tables', type_='unique')
    op.drop_index(op.f('ix_rummy_tables_join_code'), table_name='rummy_tables')
    op.create_index(op.f('ix_rummy_tables_join_code'), 'rummy_tables', ['join_code'], unique=True)
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referral_code')
    op.drop_index(op.f('ix_rummy_tables_join_code'), table_name='rummy_tables')
    op.create_index(op.f('ix_rummy_tables_join_code'), 'rummy_tables', ['join_code'], unique=False)
    op.create_unique_constraint(op.f('rummy_tables_join_code_key'), 'rummy_tables', ['join_code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('referral_settings')
    # ### end Alembic commands ###

