"""add_game_catalog

Revision ID: 692fc7699888
Revises: 404147ae6ed6
Create Date: 2026-08-19 22:59:08.137318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692fc7699888'
down_revision: Union[str, Sequence[str], None] = '404147ae6ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('game_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='game_status'), nullable=False),
    sa.Column('min_bet', sa.BigInteger(), nullable=False),
    sa.Column('max_bet', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    # ### end Alembic commands ###

    # Seed Colour Prediction game
    import uuid
    from datetime import datetime, timezone
    
    op.execute(
        f"""
        INSERT INTO games (id, name, slug, game_type, description, status, min_bet, max_bet, created_at, updated_at)
        VALUES (
            '{uuid.uuid4()}',
            'Colour Prediction',
            'colour-prediction',
            'COLOUR_PREDICTION',
            'Colour prediction game',
            'ACTIVE',
            1000,
            100000,
            NOW(),
            NOW()
        )
        """
    )


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###

