"""add_deposit_instructions

Revision ID: 6f5a7a83f66e
Revises: 1156ac2d413b
Create Date: 2026-08-18 22:47:35.232671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5a7a83f66e'
down_revision: Union[str, Sequence[str], None] = '1156ac2d413b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_configurations', sa.Column('deposit_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_configurations', 'deposit_instructions')
    # ### end Alembic commands ###

