"""add_ludo_models

Revision ID: 872b1ba979dd
Revises: 14a7ef3d2c9b
Create Date: 2026-08-20 04:23:55.636252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872b1ba979dd'
down_revision: Union[str, Sequence[str], None] = '14a7ef3d2c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ludo_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='ludo_match_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_turn_color', sa.Enum('RED', 'GREEN', 'YELLOW', 'BLUE', name='ludo_color_enum'), nullable=True),
    sa.Column('last_dice_roll', sa.Integer(), nullable=True),
    sa.Column('turn_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ludo_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.Enum('RED', 'GREEN', 'YELLOW', 'BLUE', name='ludo_color_enum'), nullable=False),
    sa.Column('seat_index', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['ludo_matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ludo_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('token_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['ludo_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ludo_tokens')
    op.drop_table('ludo_players')
    op.drop_table('ludo_matches')
    # ### end Alembic commands ###

