"""add_game_rounds_and_game_bets_tables

Revision ID: b06d1dfe2438
Revises: 0086f1f2e2d0
Create Date: 2026-08-19 20:43:43.665667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06d1dfe2438'
down_revision: Union[str, Sequence[str], None] = '0086f1f2e2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('BETTING', 'CALCULATING', 'COMPLETED', name='game_round_status'), nullable=False),
    sa.Column('result_color', sa.Enum('RED', 'GREEN', 'VIOLET', name='game_color'), nullable=True),
    sa.Column('result_number', sa.String(length=1), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('betting_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('prediction', sa.Enum('RED', 'GREEN', 'VIOLET', 'NUM_0', 'NUM_1', 'NUM_2', 'NUM_3', 'NUM_4', 'NUM_5', 'NUM_6', 'NUM_7', 'NUM_8', 'NUM_9', name='game_prediction'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('entry_fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('stake_amount', sa.BigInteger(), nullable=False),
    sa.Column('gross_win_amount', sa.BigInteger(), nullable=True),
    sa.Column('winning_fee_amount', sa.BigInteger(), nullable=True),
    sa.Column('net_win_amount', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', name='game_bet_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_bets_round_id'), 'game_bets', ['round_id'], unique=False)
    op.create_index(op.f('ix_game_bets_user_id'), 'game_bets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_bets_user_id'), table_name='game_bets')
    op.drop_index(op.f('ix_game_bets_round_id'), table_name='game_bets')
    op.drop_table('game_bets')
    op.drop_table('game_rounds')
    # ### end Alembic commands ###

