"""Add financial fields to LudoMatch

Revision ID: c7e85984cc75
Revises: 872b1ba979dd
Create Date: 2026-08-20 05:15:05.147840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e85984cc75'
down_revision: Union[str, Sequence[str], None] = '872b1ba979dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ludo_matches', sa.Column('entry_fee', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ludo_matches', sa.Column('prize_pool', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ludo_matches', sa.Column('is_settled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ludo_matches', 'is_settled')
    op.drop_column('ludo_matches', 'prize_pool')
    op.drop_column('ludo_matches', 'entry_fee')
    # ### end Alembic commands ###

